import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='p-2'>
        <header className='w-full my-2'>
          <div className='w-full flex flex-row gap-1'>
            <Link className='bg-white p-2 rounded-sm text-gray-900' href={"/"} >Trang Chủ</Link>
            <Link className='bg-white p-2 rounded-sm text-gray-900' href={"/"} >Voice</Link>
          </div>
        </header>
        {children}
        </div>
        </body>
    </html>
  )
}
